apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: student-application 
  namespace: argocd
spec: 
  project: default
  source: 
    repoURL: 
  destination:
    server: "https://kubernetes.default.svc"
    namespace: web
