apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "backend.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy | default .Values.image.pullPolicy }}
          command: [ "sh", "-c" ]
          args:
            - java -jar /app/back-end.jar --spring.config.location=file:/config/application.properties
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: DB_USER 
              valueFrom: 
                secretKeyRef: 
                  name: {{ include "backend.fullname" .}}-dbsecret
                  key: DB_USER
            - name: DB_PASS
              valueFrom: 
                secretKeyRef: 
                  name: {{ include "backend.fullname" .}}-dbsecret
                  key: DB_PASS
            - name: DB_PORT 
              value: {{ .Values.db.port | quote }}
            - name: DB_HOST 
              value: {{  printf "%s-db-svc" .Release.Name | default .Values.db.host | quote }}
            - name: DB_DATABASE 
              value: {{ .Values.db.database | quote }}
            - name: APP_NAME
              value: {{ .Chart.Name | quote }}
          volumeMounts:
            - name: config 
              mountPath: /config
              readOnly: true 
      volumes:
        - name: config
          configMap: 
            name: {{ include "backend.fullname" .}}-config 
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
